name: Deploy Lambda

on:
  workflow_call:
    inputs:
      function_name:
        description: "Lambda function name"
        required: true
        type: string
      s3_bucket:
        description: "S3 bucket where the zip is stored"
        required: true
        type: string
      s3_key:
        description: "S3 key for the lambda artifact"
        required: true
        type: string
      aws_region:
        description: "AWS region where the Lambda should be deployed"
        required: true
        type: string
      role_to_assume:
        description: "IAM role ARN assumed through GitHub OIDC"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::043189681060:role/ZeroVerifyGitHubActionsLambdaDeployment
          aws-region: ${{ inputs.aws_region }}

      - name: Update Lambda function code
        run: |
          echo "Deploying Lambda: ${{ inputs.function_name }}"
          aws lambda update-function-code \
            --function-name "${{ inputs.function_name }}" \
            --s3-bucket "${{ inputs.s3_bucket }}" \
            --s3-key "${{ inputs.s3_key }}"

      - name: Wait for Lambda update to complete
        run: |
          echo "Waiting for deployment to complete..."
          aws lambda wait function-updated \
            --function-name "${{ inputs.function_name }}"

      - name: Deployment success
        run: echo "Lambda deployed successfully!"